### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by LilleAila** [Kaffe-diem/frontend#17]
Vi bør finne en lisens til koden. Jeg foreslår GNU GPLv3.

**Comment by kluvin** [comment]
ISC? Samme for meg!

**Comment by IldenH** [comment]
I følge [wikipedia](https://en.wikipedia.org/wiki/ISC_license), "the default license for npm packages".

Det blir ISC.

**Comment by LilleAila** [comment]
ISC lar brukerene gjøre nærmest hva de vil med koden. Jeg liker personlig bedre GPLv3, fordi det er en copyleft license som blandt annet krever attribusjon og at all kode som baserer seg på dette også må være open source.
