### ISSUE TITLE
/drinks takes long to load data

### ISSUE THREAD

**Issue by LilleAila** [Kaffe-diem/frontend#19]
Finnes det noen måte å fetche data fra pocketbase raskere? Kanskje det kan caches server-side ved hjelp av svelte sin `+page.server.ts` eller lignende, da menyen ikke oppdateres så ofte.

**Comment by LilleAila** [comment]
Dette kunne for eksempel bli gjort ved å route calls til pocketbase gjennom backend (svelte) ved en GET-request som også cacher resultatet

**Comment by CarlAugust** [comment]
Jeg har lagret pb fra hooks.server.ts til Locals i app.d.ts, sånn at i en page.server.ts fil kan jeg bare ta den pb verdien, når jeg gjør dette så loader drinks dataen med en gang. Var en ganske lang samtale med chatGPT til å fungere så vet ikke om koden er optimal eller god, men den fungerer. Jeg har commited til branchen min Carl test, hvis du har lyst til å se. :)

**Comment by LilleAila** [comment]
> Jeg har lagret pb fra hooks.server.ts til Locals i app.d.ts, sånn at i en page.server.ts fil kan jeg bare ta den pb verdien, når jeg gjør dette så loader drinks dataen med en gang. Var en ganske lang samtale med chatGPT til å fungere så vet ikke om koden er optimal eller god, men den fungerer. Jeg har commited til branchen min Carl test, hvis du har lyst til å se. :)

Jeg har ikke mulighet til å teste nå, men ved første øyekast ser det bra ut. Kunne du åpnet en PR, så kan jeg reviewe den?

**Comment by IldenH** [comment]
Lukekr siden #28 er merget.
