### ISSUE TITLE
Allow message of the day notices

### ISSUE THREAD

**Issue by kluvin** [Kaffe-diem/frontend#3]
BAC: As Administrator of the payment terminal I am able to put up custom notices on the Public Display.

Tasks:
* PB database field. Message of the day.
* Change Public Display
* Change Payment Terminal

Effort: Low

**Comment by IldenH** [comment]
Hvorfor er denne issuen labelet med `blocked`?

**Comment by kluvin** [comment]
manglet statusside, ikke blokket lenger
