### ISSUE TITLE
/accounts broken?

### ISSUE THREAD

**Issue by CarlAugust** [Kaffe-diem/frontend#32]
Når jeg åpner bruker i navbaren av nettsiden så blir jeg stuck der, og så kan jeg ikke åpne noe annet i navbaren.

**Comment by IldenH** [comment]
Virker fint for meg. Har du steps to reproduce?

**Comment by CarlAugust** [comment]
![image](https://github.com/user-attachments/assets/4a1c373c-8379-441b-a903-f3074e73b8c0)

Hver gang denne erroren kommer oppstår problemet, og det ser ut som at å ikke bruke Drink fra $lib/ExpandedDrinks.svelte og istedenfor bruke p fikser problemet.

**Comment by kluvin** [comment]
ah, ser feilen. jeg faktoriserte ut noen greier fra expandeddrinks, men rakk ikke endre det før pr ble merget

**Comment by kluvin** [comment]
@CarlAugust hvis du finner feil i en dev bransje er det greit å kommentere i PR, tror det er derifra forvirringer opprinner
