### ISSUE TITLE
Komponentsystem

### ISSUE THREAD

**Issue by kluvin** [Kaffe-diem/frontend#4]
Forslag: Vi bruker https://wiredjs.com/showcase eller lignende komplekse elementer i utgangspunktet for å unngå for mye fokus på mikro design, og mer fokus på helheten av hvordan applikasjonen brukes.

**Comment by IldenH** [comment]
Jeg tror DaisyUI er bedre i det lange løp. Den har mange flere components og integrerer bedre med tailwind. Styling er også lettere å endre på.

**Comment by LilleAila** [comment]
+1

**Comment by kluvin** [comment]
Eget designsystem er bra, daisyUI funker sikkert da, enn så lenge kun 10% av tid brukes på styling inntil vi har wireframe i boks.

Enig
